//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotemSiglo21.WsReserva {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WS/", ConfigurationName="WsReserva.AgregarReserva")]
    public interface AgregarReserva {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento V_RUT_CLIENTE del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/AgregarReserva/agrRequest", ReplyAction="http://WS/AgregarReserva/agrResponse")]
        TotemSiglo21.WsReserva.agrResponse agr(TotemSiglo21.WsReserva.agrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/AgregarReserva/agrRequest", ReplyAction="http://WS/AgregarReserva/agrResponse")]
        System.Threading.Tasks.Task<TotemSiglo21.WsReserva.agrResponse> agrAsync(TotemSiglo21.WsReserva.agrRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class agrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="agr", Namespace="http://WS/", Order=0)]
        public TotemSiglo21.WsReserva.agrRequestBody Body;
        
        public agrRequest() {
        }
        
        public agrRequest(TotemSiglo21.WsReserva.agrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class agrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string V_RUT_CLIENTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string V_RUT_TRABAJADOR;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int V_NRO_MESA;
        
        public agrRequestBody() {
        }
        
        public agrRequestBody(string V_RUT_CLIENTE, string V_RUT_TRABAJADOR, int V_NRO_MESA) {
            this.V_RUT_CLIENTE = V_RUT_CLIENTE;
            this.V_RUT_TRABAJADOR = V_RUT_TRABAJADOR;
            this.V_NRO_MESA = V_NRO_MESA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class agrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="agrResponse", Namespace="http://WS/", Order=0)]
        public TotemSiglo21.WsReserva.agrResponseBody Body;
        
        public agrResponse() {
        }
        
        public agrResponse(TotemSiglo21.WsReserva.agrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class agrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public agrResponseBody() {
        }
        
        public agrResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgregarReservaChannel : TotemSiglo21.WsReserva.AgregarReserva, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgregarReservaClient : System.ServiceModel.ClientBase<TotemSiglo21.WsReserva.AgregarReserva>, TotemSiglo21.WsReserva.AgregarReserva {
        
        public AgregarReservaClient() {
        }
        
        public AgregarReservaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgregarReservaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgregarReservaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgregarReservaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TotemSiglo21.WsReserva.agrResponse TotemSiglo21.WsReserva.AgregarReserva.agr(TotemSiglo21.WsReserva.agrRequest request) {
            return base.Channel.agr(request);
        }
        
        public bool agr(string V_RUT_CLIENTE, string V_RUT_TRABAJADOR, int V_NRO_MESA) {
            TotemSiglo21.WsReserva.agrRequest inValue = new TotemSiglo21.WsReserva.agrRequest();
            inValue.Body = new TotemSiglo21.WsReserva.agrRequestBody();
            inValue.Body.V_RUT_CLIENTE = V_RUT_CLIENTE;
            inValue.Body.V_RUT_TRABAJADOR = V_RUT_TRABAJADOR;
            inValue.Body.V_NRO_MESA = V_NRO_MESA;
            TotemSiglo21.WsReserva.agrResponse retVal = ((TotemSiglo21.WsReserva.AgregarReserva)(this)).agr(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TotemSiglo21.WsReserva.agrResponse> TotemSiglo21.WsReserva.AgregarReserva.agrAsync(TotemSiglo21.WsReserva.agrRequest request) {
            return base.Channel.agrAsync(request);
        }
        
        public System.Threading.Tasks.Task<TotemSiglo21.WsReserva.agrResponse> agrAsync(string V_RUT_CLIENTE, string V_RUT_TRABAJADOR, int V_NRO_MESA) {
            TotemSiglo21.WsReserva.agrRequest inValue = new TotemSiglo21.WsReserva.agrRequest();
            inValue.Body = new TotemSiglo21.WsReserva.agrRequestBody();
            inValue.Body.V_RUT_CLIENTE = V_RUT_CLIENTE;
            inValue.Body.V_RUT_TRABAJADOR = V_RUT_TRABAJADOR;
            inValue.Body.V_NRO_MESA = V_NRO_MESA;
            return ((TotemSiglo21.WsReserva.AgregarReserva)(this)).agrAsync(inValue);
        }
    }
}
